name: VPS COLAB

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: STARTING VPS COLAB
      run: curl -sSf https://sshx.io/get | sh -s run
